<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class MealSeeder extends Seeder
{
    public function run()
    {
        DB::table('meals')->insert([
            // Keto Meals
            [
                'name' => 'Grilled Chicken Salad',
                'meal_time' => 'Lunch',
                'calories' => 275,
                'meal_type_id' => 1, // Keto
                'meal_class_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Avocado Egg Bowl',
                'meal_time' => 'Breakfast',
                'calories' => 400,
                'meal_type_id' => 1,
                'meal_class_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Keto Pancakes',
                'meal_time' => 'Breakfast',
                'calories' => 350,
                'meal_type_id' => 1,
                'meal_class_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Low-Carb Zucchini Lasagna',
                'meal_time' => 'Dinner',
                'calories' => 420,
                'meal_type_id' => 1,
                'meal_class_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Bacon & Egg Muffins',
                'meal_time' => 'Snack',
                'calories' => 150,
                'meal_type_id' => 1,
                'meal_class_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Keto Cobb Salad',
                'meal_time' => 'Lunch',
                'calories' => 380,
                'meal_type_id' => 1,
                'meal_class_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Cauliflower Mac & Cheese',
                'meal_time' => 'Dinner',
                'calories' => 420,
                'meal_type_id' => 1,
                'meal_class_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Keto Chicken Alfredo',
                'meal_time' => 'Dinner',
                'calories' => 450,
                'meal_type_id' => 1,
                'meal_class_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Keto Buffalo Wings',
                'meal_time' => 'Snack',
                'calories' => 300,
                'meal_type_id' => 1,
                'meal_class_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Keto Beef Tacos',
                'meal_time' => 'Lunch',
                'calories' => 500,
                'meal_type_id' => 1,
                'meal_class_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Vegan Meals
            [
                'name' => 'Vegan Quinoa Salad',
                'meal_time' => 'Lunch',
                'calories' => 280,
                'meal_type_id' => 2, // Vegan
                'meal_class_id' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Vegan Buddha Bowl',
                'meal_time' => 'Dinner',
                'calories' => 320,
                'meal_type_id' => 2,
                'meal_class_id' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Vegan Tofu Stir Fry',
                'meal_time' => 'Dinner',
                'calories' => 380,
                'meal_type_id' => 2,
                'meal_class_id' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Vegan Pancakes',
                'meal_time' => 'Breakfast',
                'calories' => 350,
                'meal_type_id' => 2,
                'meal_class_id' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Vegan Lentil Soup',
                'meal_time' => 'Lunch',
                'calories' => 220,
                'meal_type_id' => 2,
                'meal_class_id' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Vegan BBQ Tofu Bowl',
                'meal_time' => 'Lunch',
                'calories' => 290,
                'meal_type_id' => 2,
                'meal_class_id' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Vegan Curry',
                'meal_time' => 'Dinner',
                'calories' => 410,
                'meal_type_id' => 2,
                'meal_class_id' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Vegan Falafel Wrap',
                'meal_time' => 'Lunch',
                'calories' => 330,
                'meal_type_id' => 2,
                'meal_class_id' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Vegan Spaghetti',
                'meal_time' => 'Dinner',
                'calories' => 420,
                'meal_type_id' => 2,
                'meal_class_id' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Vegan Burrito',
                'meal_time' => 'Lunch',
                'calories' => 390,
                'meal_type_id' => 2,
                'meal_class_id' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Healthy Meals
            [
                'name' => 'Grilled Salmon Salad',
                'meal_time' => 'Lunch',
                'calories' => 310,
                'meal_type_id' => 3, // Healthy
                'meal_class_id' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Avocado Toast',
                'meal_time' => 'Breakfast',
                'calories' => 290,
                'meal_type_id' => 3,
                'meal_class_id' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Grilled Chicken & Veggies',
                'meal_time' => 'Dinner',
                'calories' => 400,
                'meal_type_id' => 3,
                'meal_class_id' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Smoothie Bowl',
                'meal_time' => 'Breakfast',
                'calories' => 300,
                'meal_type_id' => 3,
                'meal_class_id' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Healthy Turkey Wrap',
                'meal_time' => 'Lunch',
                'calories' => 360,
                'meal_type_id' => 3,
                'meal_class_id' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Veggie Stir Fry',
                'meal_time' => 'Dinner',
                'calories' => 330,
                'meal_type_id' => 3,
                'meal_class_id' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Quinoa Salad',
                'meal_time' => 'Lunch',
                'calories' => 270,
                'meal_type_id' => 3,
                'meal_class_id' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Oatmeal with Berries',
                'meal_time' => 'Breakfast',
                'calories' => 240,
                'meal_type_id' => 3,
                'meal_class_id' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Chicken Caesar Salad',
                'meal_time' => 'Lunch',
                'calories' => 300,
                'meal_type_id' => 3,
                'meal_class_id' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Steamed Veggies & Rice',
                'meal_time' => 'Dinner',
                'calories' => 280,
                'meal_type_id' => 3,
                'meal_class_id' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Grilled Salmon & Asparagus',
                'meal_time' => 'Lunch',
                'calories' => 320,
                'meal_type_id' => 4, // Diabetes
                'meal_class_id' => 4,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Vegetable Omelette',
                'meal_time' => 'Breakfast',
                'calories' => 250,
                'meal_type_id' => 4,
                'meal_class_id' => 4,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Whole Wheat Pasta with Veggies',
                'meal_time' => 'Dinner',
                'calories' => 380,
                'meal_type_id' => 4,
                'meal_class_id' => 4,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Avocado & Chicken Wrap',
                'meal_time' => 'Lunch',
                'calories' => 340,
                'meal_type_id' => 4,
                'meal_class_id' => 4,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Greek Yogurt & Berries',
                'meal_time' => 'Breakfast',
                'calories' => 180,
                'meal_type_id' => 4,
                'meal_class_id' => 4,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Quinoa & Black Bean Salad',
                'meal_time' => 'Lunch',
                'calories' => 270,
                'meal_type_id' => 4,
                'meal_class_id' => 4,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Baked Chicken with Veggies',
                'meal_time' => 'Dinner',
                'calories' => 410,
                'meal_type_id' => 4,
                'meal_class_id' => 4,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Cottage Cheese & Pineapple',
                'meal_time' => 'Snack',
                'calories' => 150,
                'meal_type_id' => 4,
                'meal_class_id' => 4,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Stir Fry Veggies with Tofu',
                'meal_time' => 'Dinner',
                'calories' => 350,
                'meal_type_id' => 4,
                'meal_class_id' => 4,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Apple with Almond Butter',
                'meal_time' => 'Snack',
                'calories' => 200,
                'meal_type_id' => 4,
                'meal_class_id' => 4,
                'created_at' => now(),
                'updated_at' => now(),
            ],

        ]);
    }
}
